# Generated by Django 5.0.1 on 2024-02-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_delete_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
            ],
        ),
    ]
