# Generated by Django 5.0.1 on 2024-02-13 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.section'),
        ),
    ]
