# Generated by Django 5.0.1 on 2024-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_tittle_section_title_movie_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='toupload/videos/'),
        ),
    ]
