# Generated by Django 5.0.1 on 2024-02-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='movie', to='movie.playlist'),
        ),
    ]
