# Generated by Django 5.0.1 on 2024-02-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
    ]
