# Generated by Django 5.0.1 on 2024-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_remove_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movie.playlist'),
        ),
    ]
