# Generated by Django 5.0.1 on 2024-02-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(default='2000-10-10'),
            preserve_default=False,
        ),
    ]
