# Generated by Django 5.0.1 on 2024-02-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customer_created_customer_liked_movies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated',
        ),
    ]
