# Generated by Django 5.0.1 on 2024-02-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_movie_release_date_alter_movie_playlists'),
        ('user', '0005_remove_customer_created_remove_customer_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='liked_movies',
            field=models.ManyToManyField(blank=True, related_name='liked_movies', to='movie.movie'),
        ),
    ]
